flyway:
   enabled: true
   baselineOnMigrate: true
   baselineVersion: 1

spring.flyway:
   enabled: true
   baselineOnMigrate: true
   baselineVersion: 1
   
#   user: sa
#   password: sa
#   url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
 
hibernate.jdbc.batch_size: 50

spring.datasource.initialize: false

event.cache.capacity: 100