create table TXNLOCK (
	TXN_ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT,
	START_TIMESTAMP TIMESTAMP,
	ACTION VARCHAR(20),
	primary key (TXN_ID)
);

create table TRANSACTION (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TYPE VARCHAR(50),
	primary key (id)
);

create table PERMISSION_ENTRY_SET (
	PERMISSION_ENTRY_SET_ID BIGINT NOT NULL AUTO_INCREMENT,
	GLOBAL_SESSION_ID VARCHAR(50) NOT NULL,
	LAST_ACCESS_TIMESTAMP TIMESTAMP,
	primary key (PERMISSION_ENTRY_SET_ID)
);

create table PERMISSION_ENTRY_SET_ACCT (
	PERMISSION_ENTRY_SET_ACCOUNT_ID BIGINT NOT NULL AUTO_INCREMENT,
	PERMISSION_ENTRY_SET_ID BIGINT NOT NULL,
	ACCOUNT_ID BIGINT,
	ACCOUNT_NAME VARCHAR(50),
	PTG_CODE VARCHAR(50),
	primary key (PERMISSION_ENTRY_SET_ACCOUNT_ID)
);

ALTER TABLE PERMISSION_ENTRY_SET_ACCT ADD CONSTRAINT fk_grade_id FOREIGN KEY (PERMISSION_ENTRY_SET_ID) REFERENCES PERMISSION_ENTRY_SET(PERMISSION_ENTRY_SET_ID);