create table TXNLOCK (
	TXN_ID NUMBER(19, 0),
	USER_ID NUMBER(19, 0),
	START_TIMESTAMP TIMESTAMP,
	ACTION VARCHAR2(20 char)
);

create table TRANSACTION (
	ID NUMBER(19, 0),
	TYPE VARCHAR2(50 char)
);
